# Generated by Django 5.2 on 2025-06-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='point_depart_habituel',
            new_name='default_end_point',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='horaire_arrivee_habituel',
            new_name='default_end_time',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='horaire_depart_habituel',
            new_name='default_start_time',
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_start_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PASSAGER', 'Passager'), ('CONDUCTEUR', 'Conducteur')], default='PASSAGER', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
